### ISSUE TITLE
Skin Module Web Set Not Working

### ISSUE THREAD

**Issue by Tanjiraaaaa** [fuji-fabric/fuji#10]
When I do /skin set web classic <URL from NameMC> 
It says unknown command probably due to the slashes and colons in the URL.

**Comment by sakurawald** [comment]
Yeah, please wrap the URL with `double quote`.

**Comment by Tanjiraaaaa** [comment]
Ooooh I see, thank you!

**Comment by Tanjiraaaaa** [comment]
The command didn't work still ;-;
![image](https://github.com/sakurawald/fuji-fabric/assets/91242022/9efecf6c-6666-44b1-bbd4-2e4bf155d346)

**Comment by sakurawald** [comment]
> The command didn't work still ;-; ![image](https://private-user-images.githubusercontent.com/91242022/335853169-9efecf6c-6666-44b1-bbd4-2e4bf155d346.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTczMjA3ODYsIm5iZiI6MTcxNzMyMDQ4NiwicGF0aCI6Ii85MTI0MjAyMi8zMzU4NTMxNjktOWVmZWNmNmMtNjY2Ni00NGIxLWJiZDQtMmU0YmYxNTVkMzQ2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjAyVDA5MjgwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM0MjZiNTViNThiMThkNWQyZTg4NzVjZTAyNGI1ZmUwN2Y0NThiZjdjMjJkNGFiYTgxYjFjYzg5OGZjODMyMWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.tsCqGG7dv7SGOZkkjVVwlnRmJntUUnyGnV6f4aN5ASY)

Please leave the mod version and i will check it.

**Comment by Tanjiraaaaa** [comment]
It's the version 1.1.8 on 1.20.6

**Comment by sakurawald** [comment]
As expected, the `URL` means `the direct url for image file`.
In this case, you should try `/skin set web classic "https://s.namemc.com/i/b08ca82cfb174380.png"`.
You can get the `direct image url` by `right click` the `download icon` and `copy link address`

**Comment by Tanjiraaaaa** [comment]
Thank you! 
This worked!
