### ISSUE TITLE
/fuji doesn't exist as a command

### ISSUE THREAD

**Issue by ShockerAttack01** [fuji-fabric/fuji#108]
How to Reproduce the bug?
No clue just added it to my mods folder for my server and it set itself up correctly but no command for /fuji
My server is running fabric version 0.16.5 minecraft version 1.20.1

What is the expected behavior?
It to add the /fuji command

What is the actual behavior?
Doesn't add the /fuji command and probably the modules don't work either

**Comment by sakurawald** [comment]
Please enable the `config module`, which provides the `/fuji reload` command.

And see if there are any errors inside your console.

**Comment by ShockerAttack01** [comment]
Is that inside the config file? I didn’t see anything modules saying config module.

**Comment by sakurawald** [comment]
> Is that inside the config file? I didn’t see anything modules saying config module.

Yes, you need to modify the `"enable": false` to `"enable": true` in `config/fuji/config.json` for `config` module.

The `fuji-manual.pdf` is written for latest version which targets on `minecraft 1.21.x`

**Comment by ShockerAttack01** [comment]
Okay thanks I look for that in the config when I can and is there anyway for me to get a Fuji manual for 1.20.1

**Comment by sakurawald** [comment]
> Okay thanks I look for that in the config when I can and is there anyway for me to get a Fuji manual for 1.20.1

Modify into this
```
...
    "config": {
      "enable": true
    },
...
```

And do a server restart after you change the value of `enable`.

However, i have to warn you that, the manual is targeted on the latest version.
In `fuji v1.1.8`, the wiki is poor. It's usable, but with some known bugs. (see: https://github.com/sakurawald/fuji/issues/62)

Some new modules in the `fuji-manual.pdf` may not exist in `fuji v1.1.8`

**Comment by sakurawald** [comment]
> Okay thanks I look for that in the config when I can and is there anyway for me to get a Fuji manual for 1.20.1

You can just reference the manual for latest version, the configuration for existing modules keeps the same sematics. Some modules may not exist in the `fuji v1.1.8`.

The `fuji v1.1.8` is an old version, it is very different from the latest version.

**Comment by ShockerAttack01** [comment]
Okay thanks
