### ISSUE TITLE
How to turn off chat format :sob:

### ISSUE THREAD

**Issue by Tanjiraaaaa** [fuji-fabric/fuji#12]
I'm not sure how to turn off chat formatting once I've done it

**Comment by sakurawald** [comment]
1. reset the personal chat format: `/chat format %message%`
2. set prefix and suffix for personal chat format: `/chat format prefix%message%suffix`

**Comment by Tanjiraaaaa** [comment]
Oooooh I didn't understand what the command did before, thanks!
