### ISSUE TITLE
Making the /head command free instead of paying

### ISSUE THREAD

**Issue by ChrysesCat** [fuji-fabric/fuji#135]
right now I can't figure out how to set the head command to free

**Comment by sakurawald** [comment]
Open the file `config/fuji/modules/head/head.json` and modify the value of `economy_type` into `FREE`, issue `/fuji reload` command.

Sorry for poor documentation.

**Comment by sakurawald** [comment]
Open the file `config/fuji/modules/head/head.json` and modify the value of `economy_type` into `FREE`, issue `/fuji reload` command.

Sorry for poor documentation.

**Comment by sakurawald** [comment]
Also, the `head module` is almost a copy of https://modrinth.com/mod/headindex at the early stage of this project, you may find this useful.

**Comment by ChrysesCat** [comment]
> Also, the `head module` is almost a copy of https://modrinth.com/mod/headindex at the early stage of this project, you may find this useful.

oki thank you, since I am already asking stuff I am working with luckperms how do I add a permission for the selector?

**Comment by sakurawald** [comment]
To assign `string permission`, it's recommended to use `luckperms` mod.
The wiki is in https://luckperms.net/wiki/Home

**Comment by ChrysesCat** [comment]
> To assign `string permission`, it's recommended to use `luckperms` mod. The wiki is in https://luckperms.net/wiki/Home

no yes but is there a fuji.permission for the gamemode switcher?

**Comment by sakurawald** [comment]
> > To assign `string permission`, it's recommended to use `luckperms` mod. The wiki is in https://luckperms.net/wiki/Home
> 
> no yes but is there a fuji.permission for the gamemode switcher?

Issue `/command-permission`, and you will find how to do that.

**Comment by sakurawald** [comment]
The `fuji.permission.<command-path>` feature requires the `luckperms` mod installed.
If you doesn't install any permission management mod, then `fuji` will fallback to use the vanilla permission system provided by `mojang`, i mean, using the `permission level` system. https://minecraft.fandom.com/wiki/Permission_level

**Comment by ChrysesCat** [comment]
> The `fuji.permission.<command-path>` feature requires the `luckperms` mod installed. If you doesn't install any permission management mod, then `fuji` will fallback to use the vanilla permission system provided by `mojang`, i mean, using the `permission level` system. https://minecraft.fandom.com/wiki/Permission_level

yeah I know, I am using luckperms! just need to figure out how to use the gamemode selector the one that uses F3+F4

**Comment by sakurawald** [comment]
> > To assign `string permission`, it's recommended to use `luckperms` mod. The wiki is in https://luckperms.net/wiki/Home
> 
> no yes but is there a fuji.permission for the gamemode switcher?

The command path of `/gamemode <game-mode-argument>` is `gamemode` and `gamemode.gamemode`.
Since the `game-mode-argument` includes all the 4 gamemodes: survival, creative, adventure and spectator.
So you can only allow all players to switch to the 4 gamemodes, or disallow them to do so.
There is no possible to specify a single gamemode.

Or you can use `command-bundle` module to create a new command like `/gms` to equals to `/gamemode spectator`

P.S:
To `allow` all players to use `/gamemode` to switch all the 4 gamemodes:
issue `/lp group default permission set fuji.permission.gamemode true`

**Comment by sakurawald** [comment]
Sorry, it seems like the `gamemode switcher` is another thing. You can read this: https://github.com/DrexHD/VanillaPermissions

If the client doesn't think they are `operator`, they will refuse to use `command block` and `gamemode switcher`. This is not about the `permission`. To support the client to use these features, another work should be done.

Since `fuji` is a `server-side only` mod, it's impossible to make the client use the `gamemode switcher` wihout some mods installed in the `client-side`. 
The mod https://modrinth.com/mod/vanilla-permissions provides the `gamemode switcher` access, and also provides the `client-side` support. You can consider it. @ChrysesCat

**Comment by sakurawald** [comment]
You can try install this mod in the `clietn-side`, which just removes the client-side permission checking, and allow you to use `gamemode switcher menu`: https://modrinth.com/mod/switcher

**Comment by sakurawald** [comment]
In conclusion, if you want to allow all players to use the `/gamemode` command:
issue the command: `/lp group default permission set fuji.permission.gamemode true`

If you want to let the client-side `gamemode switcher menu` work, the client-side requires to install: https://modrinth.com/mod/switcher, which just bypass the client-side permission checking for gamemode switcher menu.

Also, i have update the docs for `command permission module`, you can read the docs in https://github.com/sakurawald/fuji/blob/dev/docs/release/fuji.pdf

**Comment by ChrysesCat** [comment]
> In conclusion, if you want to allow all players to use the `/gamemode` command: issue the command: `/lp group default permission set fuji.permission.gamemode true`
> 
> If you want to let the client-side `gamemode switcher menu` work, the client-side requires to install: https://modrinth.com/mod/switcher, which just bypass the client-side permission checking for gamemode switcher menu.
> 
> Also, i have update the docs for `command permission module`, you can read the docs in https://github.com/sakurawald/fuji/blob/dev/docs/release/fuji.pdf

alright, btw how do I set up kits?

**Comment by sakurawald** [comment]
> > In conclusion, if you want to allow all players to use the `/gamemode` command: issue the command: `/lp group default permission set fuji.permission.gamemode true`
> > If you want to let the client-side `gamemode switcher menu` work, the client-side requires to install: https://modrinth.com/mod/switcher, which just bypass the client-side permission checking for gamemode switcher menu.
> > Also, i have update the docs for `command permission module`, you can read the docs in https://github.com/sakurawald/fuji/blob/dev/docs/release/fuji.pdf
> 
> alright, btw how do I set up kits?

The kit function is provided by `kit module`.
To create a kit, use `/kit editor`, put the items you want in the screen, keep in mind that the slot position will also keep while giving the kit to a player, so you can put armors in the right position.
To give a kit, use `/kit give <player> <kit-name>`, you can use `command_event module` to give a specific kit to a newbie player, and use `command_scheduler module` to give kit to a player automatically, or use `command_attachment module` to bind the kit giving command in a block/sign, and right click to get the kit, and use `command_cooldown module` to assign cooldown to a kit.

Now, a new cooldown mechanism for kits are in the plan.

**Comment by sakurawald** [comment]
To associate an `interval limit` and `usage limit` to a `kit`, you can use `named cooldown` provided by `command-cooldown module` introduced in `fuji v1.7.0`.

I have added some examples in the docs.
