### ISSUE TITLE
Home module suggestion

### ISSUE THREAD

**Issue by Tanjiraaaaa** [fuji-fabric/fuji#15]
# Is it possible to make only "/home" teleport you to your first set home?

![image](https://github.com/sakurawald/fuji-fabric/assets/91242022/2af24d96-c5fb-434c-81bc-4d5e9bceeebf)

**Comment by sakurawald** [comment]
The default behavior of home module supports `multi homes` by `home name`.
You need to issue `/home set first` and then `/home tp first` for example.

It's possible to add a shortcut for the first homes, but it breaks the command design logic.
However, the home module still needs more features, and current it's just a simple module.
Your suggestion is in the progress.

**Comment by sakurawald** [comment]
We have added a module named `CommandRewrite` so that you can rewrite the `/home` into `/home tp default` since `fuji-fabric v1.2.4`
