### ISSUE TITLE
add a feature to decide the level of `/enchantment` table

### ISSUE THREAD

**Issue by Itsporo** [fuji-fabric/fuji#16]
- Lost the second enchant line.
- Can you add full level enchants?

![Screenshot 2024-07-03 225042](https://github.com/sakurawald/fuji-fabric/assets/174633910/d73d1667-a6a0-40e3-a8a5-69a225884944)

**Comment by sakurawald** [comment]
Hello, `/enchantment` is a `mojang official command`, fuji doesn't provide such commands.
This issue seems no relative to `fuji-fabric` mod.

**Comment by sakurawald** [comment]
It's expected. the `enchantment` provides a `remote enchant table` with the lowest level.
Maybe we can add a feature option to decide the level of `remote enchant table`

The second enchant line appears in my client, it seems it's the default behaviour defined by mojang.
![image](https://github.com/sakurawald/fuji-fabric/assets/10484271/fb04e16e-f3e8-4dae-b7bc-382cc4a1e3b1)

**Comment by Itsporo** [comment]
Okay, thank you <3
- Regarding the loss of the second enchantment line, after I tried enchanting the item and reopening it, it was still normal. It seems like it's just a problem since I haven't enchanted it any times and don't have the enchanter achievement yet.

> It's expected. the `enchantment` provides a `remote enchant table` with the lowest level. Maybe we can add a feature option to decide the level of `remote enchant table`
> 
> The second enchant line appears in my client, it seems it's the default behaviour defined by mojang. ![image](https://private-user-images.githubusercontent.com/10484271/345529123-fb04e16e-f3e8-4dae-b7bc-382cc4a1e3b1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAwMjU0MDcsIm5iZiI6MTcyMDAyNTEwNywicGF0aCI6Ii8xMDQ4NDI3MS8zNDU1MjkxMjMtZmIwNGUxNmUtZjNlOC00ZGFlLWI3YmMtMzgyY2M0YTFlM2IxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzAzVDE2NDUwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQxMjg2YWMyODQxYWMzMjBmMTU5MDcxYjk1NGVhOWI2NDI3NmY2NWQ5MGE1ZDc4Y2JkNjY4NzRkYjdjOTk1MDgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.I9PQjkJB7Iw5r07oFMgF7MKfT2B2MbbFcdfwrGlTk-0)

**Comment by sakurawald** [comment]
> Okay, thank you <3
> 
> * Regarding the loss of the second enchantment line, after I tried enchanting the item and reopening it, it was still normal. It seems like it's just a problem since I haven't enchanted it any times and don't have the enchanter achievement yet.
> 
> > It's expected. the `enchantment` provides a `remote enchant table` with the lowest level. Maybe we can add a feature option to decide the level of `remote enchant table`
> > The second enchant line appears in my client, it seems it's the default behaviour defined by mojang. ![image](https://private-user-images.githubusercontent.com/10484271/345529123-fb04e16e-f3e8-4dae-b7bc-382cc4a1e3b1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAwMjU0MDcsIm5iZiI6MTcyMDAyNTEwNywicGF0aCI6Ii8xMDQ4NDI3MS8zNDU1MjkxMjMtZmIwNGUxNmUtZjNlOC00ZGFlLWI3YmMtMzgyY2M0YTFlM2IxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzAzVDE2NDUwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQxMjg2YWMyODQxYWMzMjBmMTU5MDcxYjk1NGVhOWI2NDI3NmY2NWQ5MGE1ZDc4Y2JkNjY4NzRkYjdjOTk1MDgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.I9PQjkJB7Iw5r07oFMgF7MKfT2B2MbbFcdfwrGlTk-0)

I test this in my minecraft client. It's confirmed that the behaviour is defined by mojang.
The enchant entry is random generated, and it's possible to be empty. You can `do an enchant` and see what's the next enchant entries in the table.

![image](https://github.com/sakurawald/fuji-fabric/assets/10484271/f19e6f7b-9f03-4d7b-9c7e-323626e9288d)

**Comment by sakurawald** [comment]
The feature is added since `fuji v1.2.3`
