### ISSUE TITLE
Continuously spamming error messages when entering /deathlog view <username> command

### ISSUE THREAD

**Issue by Itsporo** [fuji-fabric/fuji#17]
https://github.com/sakurawald/fuji-fabric/assets/174633910/d3fad419-ce81-4ba0-b45d-711b3a02b9b9

- When I enter things after the /deathlog command this starts.

**Comment by sakurawald** [comment]
Please provides the `fuji version` and the `full logs` in text (The logs you showed is cut off)

**Comment by Itsporo** [comment]
- Fuji version: fuji-1.2.1.jar
- Full logs (cut off): https://mclo.gs/sNIweTW

> Please provides the `fuji version` and the `full logs` in text (The logs you showed is cut off)

**Comment by sakurawald** [comment]
This is a bug, should be fixed in next version.

Currently, you can try this `work around`: enable `seen module` in `confug.json`

**Comment by sakurawald** [comment]
The bug is fixed in `fuji 1.2.2`. You can download the version in modrinth now.

**Comment by Itsporo** [comment]
Okay, thank you <3

> The bug is fixed in `fuji 1.2.2`. You can download the version in modrinth now.
