### ISSUE TITLE
[bug] <title> Some command responses appear differently/wrong in the console, as well as the server join message.

### ISSUE THREAD

**Issue by payphone101** [fuji-fabric/fuji#176]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Console output for its routine `/list`:
![image](https://github.com/user-attachments/assets/a87ae605-8629-4ed2-bc95-df15ec7513ba)

Player join message:
![image](https://github.com/user-attachments/assets/4eeb6b2c-bd23-4840-bc0d-ad99a03d6e30)

### Expected Behavior

Console should ouput the regular result for its commands, and join messages shouldn't result in a `playernotfound` error.

### Steps To Reproduce

1. Install fuji-3.0
2. Join server or do `/list` on server console
3. ???

### Server Logs

https://mclo.gs/DnXBPWz

### Anything else?

please check starting line `469`

**Comment by sakurawald** [comment]
Hey, the `/send-message` commands requires a player as its target.
e.g. `/send-message Steve hello, %player:name%`

If the commands is used to execute as the console, then the command should be written in the configuration file like: `send-message %player:name% hello, %player:name%`

You can find more examples in the `fuji-manual.pdf`: https://github.com/sakurawald/fuji/raw/dev/docs/release/fuji.pdf

![image](https://github.com/user-attachments/assets/2cd8ee41-553a-47a1-a3c8-7c4492344bbb)


A useful tip: you can write the command and test it in-game, and ensure it runs in-game, and then you replace the fixed player names with `%player:name%` and write it in configuration file.

**Comment by payphone101** [comment]
Hmm, I haven't changed anything upgrading from 1.6.2 -> 3.0 and was surprised to see these errors popping up. Also I have properly set up the join message to point to the placeholder `%player:name%`
[config(1).json](https://github.com/user-attachments/files/17445324/config.1.json)

**Comment by sakurawald** [comment]
> Hmm, I haven't changed anything upgrading from 1.6.2 -> 3.0 and was surprised to see these errors popping up. Also I have properly set up the join message to point to the placeholder `%player:name%` [config(1).json](https://github.com/user-attachments/files/17445324/config.1.json)

Modify `"send-message Welcome back %player:name%."` into `"send-message %player:name% Welcome back %player:name%."`, and issue `/fuji reload`, it should work.

The explanation: when executing `/send-message <player> <message>` command as console, the console will replace the `%player:name%` with contextual player name, so this is the proper syntax.

Also it's allow to color the text like `"send-message %player:name% <rainbow>Welcome back %player:name%."`

**Comment by payphone101** [comment]
That fixed the join message, but haven't found what changed the output for server issued commands like `/list` (which should just output a list of the current players online)

**Comment by payphone101** [comment]
The second line with timestamp `[20:18:59]` is what the console should output but for some reason it outputs `commands.list.players` instead
![378081445-4eeb6b2c-bd23-4840-bc0d-ad99a03d6e30](https://github.com/user-attachments/assets/03eefbfd-1fa5-4934-8765-adb3a89d26ff)

**Comment by sakurawald** [comment]
> The second line with timestamp `[20:18:59]` is what the console should output but for some reason it outputs `commands.list.players` instead ![378081445-4eeb6b2c-bd23-4840-bc0d-ad99a03d6e30](https://private-user-images.githubusercontent.com/89388404/378097963-03eefbfd-1fa5-4934-8765-adb3a89d26ff.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkzNTM0MDUsIm5iZiI6MTcyOTM1MzEwNSwicGF0aCI6Ii84OTM4ODQwNC8zNzgwOTc5NjMtMDNlZWZiZmQtMWZhNS00OTM0LTg3NjUtYWRiM2E4OWQyNmZmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDE5VDE1NTE0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNhN2U5YzExZGI1MDRjOWIwOTZjYWIwMjA1MDk2MWEzOGMzZmI0NzllZWRmODQ0MTIwY2I1ZTYyYTRhMDJiOGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.5EwkfiL5TAflHyj57ahVQUM4XMdE30xgEfq8jaijVXM)

Yeah, that's a strange thing, i have check all the modules you enabled, none of them is about the `system message`, it's not like a bug introduced by fuji.
Maybe you can recall what mods you are added or modified recently, before this strange thing happens.

**Comment by sakurawald** [comment]
> > The second line with timestamp `[20:18:59]` is what the console should output but for some reason it outputs `commands.list.players` instead ![378081445-4eeb6b2c-bd23-4840-bc0d-ad99a03d6e30](https://private-user-images.githubusercontent.com/89388404/378097963-03eefbfd-1fa5-4934-8765-adb3a89d26ff.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkzNTM0MDUsIm5iZiI6MTcyOTM1MzEwNSwicGF0aCI6Ii84OTM4ODQwNC8zNzgwOTc5NjMtMDNlZWZiZmQtMWZhNS00OTM0LTg3NjUtYWRiM2E4OWQyNmZmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDE5VDE1NTE0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNhN2U5YzExZGI1MDRjOWIwOTZjYWIwMjA1MDk2MWEzOGMzZmI0NzllZWRmODQ0MTIwY2I1ZTYyYTRhMDJiOGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.5EwkfiL5TAflHyj57ahVQUM4XMdE30xgEfq8jaijVXM)
> 
> Yeah, that's a strange thing, i have check all the modules you enabled, none of them is about the `system message`, it's not like a bug introduced by fuji. Maybe you can recall what mods you are added or modified recently, before this strange thing happens.


I guess it's about the exception occurs during the server initializing, causing the language loading process interrupted.
```
[12:00:40] [main/ERROR]: Failed to load function dke:uninstall
java.util.concurrent.CompletionException: java.lang.IllegalArgumentException: Whilst parsing command on line 1: argument.entity.toomany at position 0: <--[HERE]
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315) ~[?:?]
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320) ~[?:?]
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1770) ~[?:?]
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760) ~[?:?]
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387) ~[?:?]
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312) ~[?:?]
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843) ~[?:?]
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808) ~[?:?]
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188) ~[?:?]
Caused by: java.lang.IllegalArgumentException: Whilst parsing command on line 1: argument.entity.toomany at position 0: <--[HERE]
	at net.minecraft.server.function.CommandFunction.create(CommandFunction.java:80) ~[server-intermediary.jar:?]
	at net.minecraft.server.function.FunctionLoader.method_29451(FunctionLoader.java:89) ~[server-intermediary.jar:?]
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
	... 6 more
[12:00:40] [main/ERROR]: Couldn't load advancements: [minecraft:wander_add_map, minecraft:give_quest_trader_trade]
```

Maybe you should fix this exception, and see if this problem exists.

Also, another guess: try disable the mod `infinitetrading` and see if this bug exists.

**Comment by payphone101** [comment]
will do and report back

**Comment by payphone101** [comment]
it was the mod `Dragonkind Evolved` although installing the datapack version didn't affect anything. Anyways the fix for `server join` messages with the target selector did work so I'm closing the ticket. Thanks again for the assist :)

**Comment by sakurawald** [comment]
> it was the mod `Dragonkind Evolved` although installing the datapack version didn't affect anything. Anyways the fix for `server join` messages with the target selector did work so I'm closing the ticket. Thanks again for the assist :)

You are welcomed.
