### ISSUE TITLE
Can you create a discord server for convenient communication or Q&A?

### ISSUE THREAD

**Issue by Itsporo** [fuji-fabric/fuji#19]
The mod you made is really great because it adds features from a server that uses plugins to a server that uses mods <3

**Comment by sakurawald** [comment]
It's happy to hear that you like this mod. We used to have a discord server, but we close the server due to little people. We'll consider open another discord server after `fuji` mod go further and becomes more complete.
You can ask questions using `github issue` currently, it's open and anyone here can help you.

**Comment by sakurawald** [comment]
We recently build a wiki in https://github.com/sakurawald/fuji-fabric/wiki, hope this will be useful.

**Comment by sakurawald** [comment]
We've write a wiki generator recently, and more detailed information can be seen in https://github.com/sakurawald/fuji-fabric/wiki/Configuration

**Comment by sakurawald** [comment]
More work should be put in the build of wiki. We are considering to provide a clear and easy-to-read wiki.

**Comment by iamnotbobby** [comment]
> It's happy to hear that you like this mod. We used to have a discord server, but we close the server due to little people. We'll consider open another discord server after `fuji` mod go further and becomes more complete. You can ask questions using `github issue` currently, it's open and anyone here can help you.

Is there still plans to open a Discord server? It'd be really nice :)

**Comment by sakurawald** [comment]
> Is there still plans to open a Discord server? It'd be really nice :)

You can add my discord account, I will reply if I see it.
