### ISSUE TITLE
Seems as if the commands just aren't working

### ISSUE THREAD

**Issue by NickNookNeo** [fuji-fabric/fuji#200]
### Are you using the latest available version for your server?

- [X] I am using the latest available version of fuji for my minecraft server.

### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Current Behavior

None of the non default commands work (by default I mean "inspect" and things like that.)

### Expected Behavior

the commands do not show up on the list nor are they runnable by me (an op) like expected

**Comment by sakurawald** [comment]
Please provide the version of `fuji` you are using.

The command `/fuji` is provided by the `fuji module`, so you have to enable this module in `config/fuji/config.json`, and restart the server to apply this change.

All other commands are provided by standalone modules, for example:
- The `afk module` provides the `/afk` command and its related functionality.
- The `tpa module` provides the `/tpa`, `/tpahere`, `/tpaaccept` and `/tpadeny` commands.
- ...
