### ISSUE TITLE
[bug] Placeholders not working 1.21.1

### ISSUE THREAD

**Issue by TinyMandalorian** [fuji-fabric/fuji#201]
### Are you using the latest available version for your server?

- [X] I am using the latest available version of fuji for my minecraft server.

### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Current Behavior

![image](https://github.com/user-attachments/assets/5e83f271-553e-4cad-a3ce-45484c09b055)
I have text placeholderapi installed

**Comment by sakurawald** [comment]
1. The `Text Placeholder API` mod is **embedded** in `fuji`, so you don't need to install it.
2. The placeholders like `%fuji:player_moved%` is provided by `placeholder module`: you need to enable this module in `config/fuji/config.json`, and restart the server to apply this change.

**Comment by TinyMandalorian** [comment]
ohhhhhhhhhhhhh ty this fixed it
