### ISSUE TITLE
[bug] whenever i reload the config the config restores to its default config

### ISSUE THREAD

**Issue by TinyMandalorian** [fuji-fabric/fuji#202]
### Are you using the latest available version for your server?

- [X] I am using the latest available version of fuji for my minecraft server.

### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Current Behavior

for example im trying to mess with the command_event module i removed all the events except for the join events but it resets to default whenever I reload the mod or restart the server no errors

**Comment by sakurawald** [comment]
If you want to delete all **commands** in an event, just write:
```
...
"command_list": []
...
```
This is the properly semantics.

If you delete the whole `command_list` in the configuration, then it means a broken structure, fuji will try to fix this by generating a default configuration.
