### ISSUE TITLE
How do I set permissions with the PlayerRoles mod?

### ISSUE THREAD

**Issue by Tanjiraaaaa** [fuji-fabric/fuji#21]
How do I set permissions with the PlayerRoles mod? Or is it not possible 🤔 
Also, could you make a 1.2.4 version for 1.20.6, please?

**Comment by sakurawald** [comment]
It seems like the mod `PlayerRoles` do the same thing with `Fuji`.
The module `CommandPermission` is only used to `override` the `permissin node`, and expected to work wirh `LuckPerms`.

The codebase of minecraft changes in every version, so it requires time to back-port and support multi versions. I will try it if i have time.

**Comment by sakurawald** [comment]
We create a partial back-port which includes the bug-fix and new features from `fuji v1.2.4`
See: https://modrinth.com/mod/fuji/version/1.2.4-partial-backport
