### ISSUE TITLE
[bug?] Custom home.json Being Overwritten

### ISSUE THREAD

**Issue by cecaelion** [fuji-fabric/fuji#216]
### Are you using the latest available version for your server?

- [X] I am using the latest available version of fuji for my minecraft server.

### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Current Behavior

Hello! The server I run is switching from Essentials Commands to Fuji for efficiency purposes. I am trying to create Fuji homes for players based on their EC homes, with the same names and coordinates, by editing `config/fuji/modules/home/home.json`. However, when I reboot the server, this file gets overwritten by a new copy. 

### Expected Behavior

I expected the mod to use the edited `home.json` file.

### Steps To Reproduce

1. Shut down server.
2. Edit the file `config/fuji/modules/home/home.json` to include your username, a named home, and valid coordinates in the proper format. 
3. Reboot server and join.
4. Run `/home list`
5. No homes will come up.

### Server Logs

https://mclo.gs/XezjBtp

### Anything else?

This is the `home.json` I was trying to use: [home.json](https://github.com/user-attachments/files/17852122/home.json)

**Comment by sakurawald** [comment]
Hello, fuji only generate the default configuration structure if it's **missing** or **syntax-error**.

As you can see, there is an error in `gson syntax`. **You should delete the trailing comma** in column 1076.

Also, there should be an error in the console **the first time** when fuji loads this file and overrides this file.
![image](https://github.com/user-attachments/assets/ce09357b-38e9-4a93-8173-005a2508d99b)

**Comment by sakurawald** [comment]
Please let met konw if the problem is addressed.

**Comment by cecaelion** [comment]
Thank you so much! It's weird, for some reason it did notify me of another syntax method earlier.
