### ISSUE TITLE
Blocks not updating in the 1.2.4-partial-backport version

### ISSUE THREAD

**Issue by Tanjiraaaaa** [fuji-fabric/fuji#22]
The bug can be seen in [this video](https://drive.google.com/file/d/1oD3nGRgtb6JM-a2iDNFWysK9IxwoWIbf/view?usp=sharing)

I'm not sure if it's because blocks not updating or not, but killing mobs still drops like normal.
I have confirmed that it is because of Fuji as when I degraded to 1.2.0, it worked like normal again.

**Comment by sakurawald** [comment]
Confirmed. Some events are changed in the latest version. I forget to register these events in the backport version. To avoid this case happen again, we have a plan to write some programs to detect this.

I am sorry for that, a fixed version has publish in the modrinth.
