### ISSUE TITLE
[feature] Support wildcards for anti_build like in essentials

### ISSUE THREAD

**Issue by phaldan** [fuji-fabric/fuji#224]
### Is there an existing request for feature?

- [X] I have searched the existing issues

### What feature would you like?

Thx for all the work you have put into this mod. I have a small feature request.

I would like to disable by default placing any kind of blocks. The anti_build modules with place_block technically already supports this, but I have to add a list of all the available blocks. Essentials has a way to achieve this by using a wildcard (See Permission Control on https://wiki.ess3.net/wiki/AntiBuild).

This would be interesting for all types of anti_build (break_block, place_block, interact_item, interact_block, interact_entity).

A config could look like:
```
{
  "anti": {
    "place_block": true
  }
}
```

Alternative:
```
{
  "anti": {
    "place_block": {
      "all": true
    }
  }
}
```

Another:
```
{
  "anti": {
    "place_block": {
      "id": ["*"]
    }
  }
}
```

**Comment by sakurawald** [comment]
Hello, thanks for you report. This would be a good thing to have, but i recently have no time until 2025 middle, this would be done after that.

**Comment by phaldan** [comment]
The main change would be in "AntiBuildInitializer". I can create a small PR to introduce this feature. Do you prefer one of the config variants?
