### ISSUE TITLE
CommandRewrite isn't working

### ISSUE THREAD

**Issue by Tanjiraaaaa** [fuji-fabric/fuji#25]
![image](https://github.com/sakurawald/fuji-fabric/assets/91242022/d43ba78a-a01e-4be5-a6c2-ab948c9343d1)
![image](https://github.com/sakurawald/fuji-fabric/assets/91242022/c0fcc40d-f67c-4a21-b7b3-5e4314502843)

**Comment by sakurawald** [comment]
Hello, is there any error message in console? Or Is the `HomeModule` enabled?

**Comment by Tanjiraaaaa** [comment]
It is enabled. I'll check the console later

**Comment by sakurawald** [comment]
> It is enabled. I'll check the console later

After you enable a module in `config.json`, you need to reboot the server.
The command `/fuji reload` is only used to reload options. You can't enable a module if the server is already started.

**Comment by Tanjiraaaaa** [comment]
> > It is enabled. I'll check the console later
> 
> After you enable a module in `config.json`, you need to reboot the server. The command `/fuji reload` is only used to reload options. You can't enable a module if the server is already started.

Oh I didn't know that, that's probably why then, thanks!
