### ISSUE TITLE
Resource world cannot load

### ISSUE THREAD

**Issue by yizexiaomu** [fuji-fabric/fuji#29]
When players use the command to tp to the resource world, they cannot load the resource world
It has been confirmed that this issue only appears in the most recent versions, and it did not occur in version 1.2.7, so it is not a problem with other modules
[latest.log](https://github.com/user-attachments/files/16362510/latest.log)

**Comment by sakurawald** [comment]
The random teleport codes are not modified since many version ago.
It's possible the compatibility between fuji and c2me.

Will added a better compatible method to fix this.

**Comment by sakurawald** [comment]
A better compatible method for random teleport is used since v1.3.3
