### ISSUE TITLE
add permission for `chat` formats

### ISSUE THREAD

**Issue by sakurawald** [fuji-fabric/fuji#3]
添加新的权限以控制Chat模块的格式化代码使用, 如颜色代码, 动作代码等..

**Comment by mcjunshi** [comment]
chat还可以加个网址提示

**Comment by sakurawald** [comment]
> chat还可以加个网址提示

请详细提供该用例的描述. 
目前已知Minecraf原版在发送链接时, 会自动转化网址.

**Comment by mcjunshi** [comment]
![image](https://github.com/sakurawald/fuji-fabric/assets/132731965/a70691fe-b527-4ecb-9e7a-b08bab73ddad)
不知为啥我这边发送链接，点击没反应

**Comment by sakurawald** [comment]
> ![image](https://private-user-images.githubusercontent.com/132731965/295514788-a70691fe-b527-4ecb-9e7a-b08bab73ddad.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUxNzYwNzEsIm5iZiI6MTcwNTE3NTc3MSwicGF0aCI6Ii8xMzI3MzE5NjUvMjk1NTE0Nzg4LWE3MDY5MWZlLWI1MjctNGVjYi05ZTdhLWIwOGJhYjczZGRhZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDExM1QxOTU2MTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04ZTA2MzQwNzAxOGNhZDQ1MmI3ZjZjZjBkMTUxNzA5MWFiODVkZGYwNzkwNTRmNDJiYzU4M2M0ZTMwNDZiOTAzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.VLSTHdzLolV8Bff1QwvLx5ks-lvk2pENaE37WoWy-U4) 不知为啥我这边发送链接，点击没反应

参考MiniMessage格式文档, 应该加上action: open_url

**Comment by mcjunshi** [comment]
我的意思我这原版不会转换为网址
我自己写了一个[ChatModule.txt](https://github.com/sakurawald/fuji-fabric/files/14340843/ChatModule.txt)

**Comment by sakurawald** [comment]
> 我的意思我这原版不会转换为网址 我自己写了一个[ChatModule.txt](https://github.com/sakurawald/fuji-fabric/files/14340843/ChatModule.txt)

很好, 你可以提请一个PR, 测试通过的话即可合并.
另外, 请将Component.text()中的文本替换为通过key获取的text. (见lang util)

**Comment by mcjunshi** [comment]
> > 我的意思，我这原版不会转换为网址 我自己写了一个[ChatModule.txt](https://github.com/sakurawald/fuji-fabric/files/14340843/ChatModule.txt)
> 
> 很好， 你可以提请一个PR， 测试通过的话即可合并. 另外， 请将Component.text（）中的文本替换为通过key获取的text.（见lang util）

好，谢谢！我提交了

**Comment by sakurawald** [comment]
This feature will be included in next version.
