### ISSUE TITLE
The chat module's feature "pos" show in certain words

### ISSUE THREAD

**Issue by Tanjiraaaaa** [fuji-fabric/fuji#30]
![image](https://github.com/user-attachments/assets/d4b637ab-b11f-4af8-be94-f9e1481583ad)

**Comment by sakurawald** [comment]
Hello, which version of fuji are you using ?

**Comment by Tanjiraaaaa** [comment]
> Hello, which version of fuji are you using ?

I'm using the 1.2.4 backport

**Comment by sakurawald** [comment]
> > Hello, which version of fuji are you using ?
> 
> I'm using the 1.2.4 backport

Around v1.2.4, there is a bug in chat module, which cause the `pos` feature mis-parsed, and sad that this feature can't be disabled in v1.2.4.

We fixed the bug in the later version, and in the latest version, the feature `pos` is fixed, and can be disable.

**Comment by Tanjiraaaaa** [comment]
> > > Hello, which version of fuji are you using ?
> > 
> > 
> > I'm using the 1.2.4 backport
> 
> Around v1.2.4, there is a bug in chat module, which cause the `pos` feature mis-parsed, and sad that this feature can't be disabled in v1.2.4.
> 
> We fixed the bug in the later version, and in the latest version, the feature `pos` is fixed, and can be disable.

Oh I see, will there be a backport for the newest version as well?

**Comment by sakurawald** [comment]
Huh, the backport is hard, since v1.21 version changes a lot. (about 300+ files are different).

**Comment by sakurawald** [comment]
However, i just publish a version fixed the bug. 

See: https://modrinth.com/mod/fuji/version/38Julpmc
