### ISSUE TITLE
Is it possible for this mod to add a module with the ability to format what is displayed on the console?

### ISSUE THREAD

**Issue by Itsporo** [fuji-fabric/fuji#37]
- Sorry if this may be annoying and extra work for you.
- I want to ask that because the chat module allows using chat format but the console when viewed will not see anything so I want to suggest adding this module.
- It will be a bit difficult to understand because I'm not good at English so I use google translate.

**Comment by sakurawald** [comment]
Will be added in next version.

**Comment by yizexiaomu** [comment]
Making the console more complex may lead to problems with the operation of MCDR. I am not sure how the specific author should implement it, but after installing this mod,（https://modrinth.com/mod/better-fabric-console） players will not be able to use MCDR commands on the server, and there may also be other unexpected situations

**Comment by sakurawald** [comment]
> Making the console more complex may lead to problems with the operation of MCDR. I am not sure how the specific author should implement it, but after installing this mod,（[https://modrinth.com/mod/better-fabric-console）](https://modrinth.com/mod/better-fabric-console%EF%BC%89) players will not be able to use MCDR commands on the server, and there may also be other unexpected situations

There will be an option to enable/disable it, and of course, new feature will always be disabled by default, to avoid surprise to users.

**Comment by Itsporo** [comment]
> Will be added in next version.

Thank you!

**Comment by sakurawald** [comment]
added since v1.3.5

**Comment by Itsporo** [comment]
> added since v1.3.5

Thank you!
