### ISSUE TITLE
Expand antibuild module

### ISSUE THREAD

**Issue by Itsporo** [fuji-fabric/fuji#39]
- Me and my friend were chatting about this module. I wonder if it is possible to update features similar to worldguard plugin in bukkit for this module.
- https://enginehub.org/worldguard
- Sorry for the amount of work I put on you. If it is not feasible, please tell me directly.

**Comment by sakurawald** [comment]
Worldguard mod is another type of `generic protection mod`.
It's recommend you use the the following mods:
1. https://modrinth.com/mod/leukocyte
2. https://modrinth.com/mod/enclosure (Port the `residence plugin` into fabric, I am also one of the contributor)

**Comment by Itsporo** [comment]
> Worldguard mod is another type of `generic protection mod`. It's recommend you use the the following mods:
> 
> 1. https://modrinth.com/mod/leukocyte
> 2. https://modrinth.com/mod/enclosure (Port the `residence plugin` into fabric, I am also one of the contributor)

- Enclosure is it 100% for admins only? I read it and it seems like a claim for players. My friend wants to make a safe zone in the server but hasn't found a suitable mod yet.
- Leukocyte i wrote an issue asking about upgrading to 1.21 they responded but still no update.

**Comment by sakurawald** [comment]
> > Worldguard mod is another type of `generic protection mod`. It's recommend you use the the following mods:
> > 
> > 1. https://modrinth.com/mod/leukocyte
> > 2. https://modrinth.com/mod/enclosure (Port the `residence plugin` into fabric, I am also one of the contributor)
> 
> * Enclosure is it 100% for admins only? I read it and it seems like a claim for players. My friend wants to make a safe zone in the server but hasn't found a suitable mod yet.
> * Leukocyte i wrote an issue asking about upgrading to 1.21 they responded but still no update.

Enclosure or residence can replace worldguard, since you can also create a `zone` which includes the whole dimension, as you want. And you can also set lots of `flags`. It's a alternative to `worldguard`, and better.

Worldguard allows you to create zones with flags, so are enclosure/residence.

**Comment by Itsporo** [comment]
> > > Worldguard mod is another type of `generic protection mod`. It's recommend you use the the following mods:
> > > 
> > > 1. https://modrinth.com/mod/leukocyte
> > > 2. https://modrinth.com/mod/enclosure (Port the `residence plugin` into fabric, I am also one of the contributor)
> > 
> > 
> > 
> > * Enclosure is it 100% for admins only? I read it and it seems like a claim for players. My friend wants to make a safe zone in the server but hasn't found a suitable mod yet.
> > * Leukocyte i wrote an issue asking about upgrading to 1.21 they responded but still no update.
> 
> Enclosure or residence can replace worldguard, since you can also create a `zone` which includes the whole dimension, as you want. And you can also set lots of `flags`. It's a alternative to `worldguard`, and better.
> 
> Worldguard allows you to create zones with flags, so are enclosure/residence.

Okay, thank you so much!
