### ISSUE TITLE
CommandAlias seems to have a problem.

### ISSUE THREAD

**Issue by Tanjiraaaaa** [fuji-fabric/fuji#40]
Everytime I try to join a world with CommandAlias set to true, it crashes Minecraft entirely.
It works fine once I turn it off.
Here's the [crash log.](https://mclo.gs/CRuPcS1)

**Comment by sakurawald** [comment]
Known issue, fixed since `v1.3.3`, please use the latest version for `mc 1.21`

**Comment by Tanjiraaaaa** [comment]
I see, thanks!
