### ISSUE TITLE
Issue about the Tablist module

### ISSUE THREAD

**Issue by owoBeluga** [fuji-fabric/fuji#41]
hey! I recently found Fuji on bilibili and i would like to say the mod you made is really great
but theres a issue on the tablist module while im debuging the config,that is the player avatar in tablist is not the player's own,its a skin just like the default steve skin like this

![image](https://github.com/user-attachments/assets/f6eab82a-d4d0-4658-b002-632e286af8a7)

i dont know why this is happened and i cannot find any arguments to modify this
could u tell me how to fix this issue? Thanks a lot <3

**Comment by owoBeluga** [comment]
sry for bothering
after some debugging i fixed this issue

**Comment by sakurawald** [comment]
Did you enable the `tablist.sort` module ?

Currently, the `tablist.sort` module will not copy the `original player`'s skin, but it will be a feature to do so.

**Comment by sakurawald** [comment]
> Did you enable the `tablist.sort` module ?
> 
> Currently, the `tablist.sort` module will not copy the `original player`'s skin, but it will be a feature to do so.

The feature will be added since `v1.3.6`
