### ISSUE TITLE
Custom data formater for placeholder %fuji:date%

### ISSUE THREAD

**Issue by sakurawald** [fuji-fabric/fuji#43]
https://github.com/sakurawald/fuji-fabric/issues/18#issuecomment-2258424096

**Comment by sakurawald** [comment]
Will be added since `v1.3.6`

**Comment by Itsporo** [comment]
- The format of %fuji:date% remains unchanged.
![2024-08-01_15 59 23](https://github.com/user-attachments/assets/b12b9bb7-b27a-49f7-ac00-0f9af5bd7a0e)

**Comment by sakurawald** [comment]
> * The format of %fuji:date% remains unchanged.
>       ![2024-08-01_15 59 23](https://private-user-images.githubusercontent.com/174633910/354158214-b12b9bb7-b27a-49f7-ac00-0f9af5bd7a0e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI1MTE2MDAsIm5iZiI6MTcyMjUxMTMwMCwicGF0aCI6Ii8xNzQ2MzM5MTAvMzU0MTU4MjE0LWIxMmI5YmI3LWIyN2EtNDlmNy1hYzAwLTBmOWFmNWJkN2EwZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgwMVQxMTIxNDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zODBjMTBjZDRkYzM1MjY4ZDU3YWI2ZTUzY2FkMzg4Y2Y4MDhhMjRkNWE5MGE1ODgxMjlmZGM0NjA2YTcwMWQwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.mhA1jn6-_mFx8eLrKzT_vm2HvUH8mqVzMPfxmI2DZuM)

Please read the wiki, now the placeholder can accept an optional args to custom `date formatter`.

**Comment by Itsporo** [comment]
> > * The format of %fuji:date% remains unchanged.
> >   ![2024-08-01_15 59 23](https://private-user-images.githubusercontent.com/174633910/354158214-b12b9bb7-b27a-49f7-ac00-0f9af5bd7a0e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI1MTE2MDAsIm5iZiI6MTcyMjUxMTMwMCwicGF0aCI6Ii8xNzQ2MzM5MTAvMzU0MTU4MjE0LWIxMmI5YmI3LWIyN2EtNDlmNy1hYzAwLTBmOWFmNWJkN2EwZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgwMVQxMTIxNDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zODBjMTBjZDRkYzM1MjY4ZDU3YWI2ZTUzY2FkMzg4Y2Y4MDhhMjRkNWE5MGE1ODgxMjlmZGM0NjA2YTcwMWQwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.mhA1jn6-_mFx8eLrKzT_vm2HvUH8mqVzMPfxmI2DZuM)
> 
> Please read the wiki, now the placeholder can accept an optional args to custom `date formatter`.

Sorry for my hand being faster than my brain, I just checked the wiki again. I think this change will be adjusted in the source code and not in the config

**Comment by sakurawald** [comment]
> > > * The format of %fuji:date% remains unchanged.
> > >   ![2024-08-01_15 59 23](https://private-user-images.githubusercontent.com/174633910/354158214-b12b9bb7-b27a-49f7-ac00-0f9af5bd7a0e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI1MTE2MDAsIm5iZiI6MTcyMjUxMTMwMCwicGF0aCI6Ii8xNzQ2MzM5MTAvMzU0MTU4MjE0LWIxMmI5YmI3LWIyN2EtNDlmNy1hYzAwLTBmOWFmNWJkN2EwZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgwMVQxMTIxNDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zODBjMTBjZDRkYzM1MjY4ZDU3YWI2ZTUzY2FkMzg4Y2Y4MDhhMjRkNWE5MGE1ODgxMjlmZGM0NjA2YTcwMWQwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.mhA1jn6-_mFx8eLrKzT_vm2HvUH8mqVzMPfxmI2DZuM)
> > 
> > 
> > Please read the wiki, now the placeholder can accept an optional args to custom `date formatter`.
> 
> Sorry for my hand being faster than my brain, I just checked the wiki again. I think this change will be adjusted in the source code and not in the config

Hub, the args way is more flexible than the hard-coded way. And the Java default date formatter is a powerful tool, so you can custom it however you wish.
