### ISSUE TITLE
Is it possible to add `Warp` function?

### ISSUE THREAD

**Issue by Hiusi** [fuji-fabric/fuji#47]
Hi! I absolutely love this mod! However, if possible, I need a `warp` function.

Why do I need `warp` when `home` and `tpa` exist?

In my case, I have predetermined positions for school, shop, arena, etc. I usually use HuskHomes's `/warp school` and `/warp set school` to set a global warp location at my standing position.

I hope my request is easy to understand.

**Comment by sakurawald** [comment]
Added since `v1.3.7`. You might want to check `works module`, which provides full gui support teleporation.

**Comment by Hiusi** [comment]
omg thank you for the warp feature! if I want to add cooldown between each warp, is my config correct?
```
"command_cooldown": {
      "enable": true,
      "regex2ms": {
        "download\\s*": 120000,
        "rw tp (overworld|the_nether|the_end)": 120000,
        "chunks\\s*": 60000,
        "warp\\s*": 30000
      }
    },
```

**Comment by sakurawald** [comment]
> Author

It's correct. You can also write `"warp tp \\s*": 30000`.
The `regex` is a language about string pattern match, it's a powerful language to describe how to match a specific string pattern, and it's easy once you understand it.
You can search a lot information about `regex` language on the Internet.

See also
- https://www.youtube.com/watch?v=sXQxhojSdZM
- https://www.youtube.com/watch?v=rhzKDrUiJVk
