### ISSUE TITLE
Fix tablist skin reloading

### ISSUE THREAD

**Issue by Itsporo** [fuji-fabric/fuji#48]
- In version 1.3.6, you have just fixed the skin display error in tablist.sort. However, it is quite inconvenient because when players change skin in FabircTailor mod, they will have to exit the server and re-enter for the new skin to be updated on the tablist. Can this problem be fixed?

**Comment by sakurawald** [comment]
I see, it's about the game profile de-sync, this will be fixed in next version, so the skin will get updated in tab list, without re-connect.

**Comment by sakurawald** [comment]
Should be fixed since `v1.3.7`

**Comment by Itsporo** [comment]
Thank you so much, your mod updates are fast even though you said you don't have much free time.

**Comment by Itsporo** [comment]
> Should be fixed since `v1.3.7`

A new bug occurs that causes players to disappear from the tab list when the interface is reloaded or when another player joins the server. (players will reappear after about 5 seconds)

**Comment by sakurawald** [comment]
> > Should be fixed since `v1.3.7`
> 
> A new bug occurs that causes players to disappear from the tab list when the interface is reloaded or when another player joins the server. (players will reappear after about 5 seconds)

I will check it. There will be another update about tablist module.

**Comment by sakurawald** [comment]
> > Should be fixed since `v1.3.7`
> 
> A new bug occurs that causes players to disappear from the tab list when the interface is reloaded or when another player joins the server. (players will reappear after about 5 seconds)

The bug about de-sync of game-profile is fixed in `v1.3.8`. And also, it's now a sub-module named `tablist.sort.sync_game_profile`, which you can enable or disable it.

**Comment by Itsporo** [comment]
> > > Should be fixed since `v1.3.7`
> > 
> > 
> > A new bug occurs that causes players to disappear from the tab list when the interface is reloaded or when another player joins the server. (players will reappear after about 5 seconds)
> 
> The bug about de-sync of game-profile is fixed in `v1.3.8`. And also, it's now a sub-module named `tablist.sort.sync_game_profile`, which you can enable or disable it.

Thank you very much, I just tried and this problem is fixed.
