### ISSUE TITLE
[Feature Request] is it possible to request NameTag Customization? 

### ISSUE THREAD

**Issue by UwUCookies-mc** [fuji-fabric/fuji#49]
first I love this mod so much, this mod singlehandedly replace 6 of my mods and that is super amazing!! but now that one month since I use your mod, I want to use fuji's blockmined and prefix on player nametag is that possible?
Thank you  ( ´ ∀ )ノ～ ♡

**Comment by sakurawald** [comment]
I am glad that you love it. There is nothing special about fuji's `placeholders`.
All the `placeholder` are registered in `Text Placeholder API` (https://modrinth.com/mod/placeholder-api), and any of mods that support this API can use fuji's placeholders.

Currently, fuji doesn't provide a module about `custom player's nametag`, it will be done once i have more spare time.

**Comment by sakurawald** [comment]
Hello, there is an existing mod that does this: https://modrinth.com/mod/customnametags

**Comment by sakurawald** [comment]
I just implement a simple nametag module in `fuji v1.4.8`, which is based on polymer virtual entity api.
