### ISSUE TITLE
[Feature Request]Image module

### ISSUE THREAD

**Issue by yizexiaomu** [fuji-fabric/fuji#55]
Present network images on the server without adding items

**Comment by sakurawald** [comment]
Currently, fuji focus more on the more basic structures, which have better interaction with other functions, and will greatly help the server maintainers.

This issue is marked as an `extra function`, with low-priority.
Anyone else is welcomed to implement this function.

**Comment by sakurawald** [comment]
There is a mod exists named `Image2Map` for this purpose.
Close this issue for reasons:
1. reduce the duplication of the work.
2. the purpose is not the focus of fuji in current stage.

Recommended mod: https://modrinth.com/mod/image2map
