### ISSUE TITLE
Help with carpet module configuration items

### ISSUE THREAD

**Issue by DEEP-IOS** [fuji-fabric/fuji#61]
My Minecraft version is 1.20.1, and the mod version is 1.1.8. I can't find the carpet-related configuration items in the config file. I am sure that I have installed carpet normally.

**Comment by sakurawald** [comment]
For `mc 1.20.1` version.
You need to install `spark` before you enable `profiler` module.
You need to install `carpet` before you enable `better info` and `better fake player` module.

However, `fuji` in `mc 1.20.1` is usable but not recommended. Fuji gets lots of updates in `mc 1.21` version.

The official wiki is targeted on `mc 1.21` and there is no wiki available for `mc 1.20.1`.

**Comment by sakurawald** [comment]
Close this issue because there is no replies. Hope my answer can help you. You are welcome to ask new questions.
