### ISSUE TITLE
feature request: add /invsee and /endersee

### ISSUE THREAD

**Issue by fucksophie** [fuji-fabric/fuji#67]
Fuji is currently missing:
```
/sudo 
/invsee and /endersee
```

`/invsee <player>` lets moderators see other people's inventory
`/endersee <player>` lets moderators see other people's ender chest

`/sudo <player> <command>` lets moderators run commands as other people. There should also be a sudo command like `/sudo Notch c:Hello World` that sends a message, like EssentialsX.

Essentials-commands does have these, but it's non-FOSS and I'd like not to use it.

**Comment by sakurawald** [comment]
The `/sudo` is in `run module`, using: `/run as fake-op ...`.
The output commands: are `/send-message`, `/send-broadcast`, `/send-title`, `/send-actionbar` and `/send-toast`.

**Comment by sakurawald** [comment]
The `/invsee` and `/endersee` is in the plan.

**Comment by fucksophie** [comment]
> The `/sudo` is in `run module`, using: `/run as fake-op ...`. The output commands: are `/send-message`, `/send-broadcast`, `/send-title`, `/send-actionbar` and `/send-toast`.

Sudo with `sudo <name> c:Hi` will send a message to everybody, as that user. Like
`/sudo Notch c:Hi!`
`Notch: Hi!`

This can be .. kinda horribly recreated with fuji's current tools, but it just looks horrible.
`/execute as @a run run as fake-op @s send-broadcast %fuji:player_prefix%%player:displayname_visual%%fuji:player_suffix%: Hi`

**Comment by sakurawald** [comment]
> Fuji is currently missing:
> 
> ```
> /sudo 
> /invsee and /endersee
> ```
> 
> `/invsee <player>` lets moderators see other people's inventory `/endersee <player>` lets moderators see other people's ender chest
> 
> `/sudo <player> <command>` lets moderators run commands as other people. There should also be a sudo command like `/sudo Notch c:Hello World` that sends a message, like EssentialsX.
> 
> Essentials-commands does have these, but it's non-FOSS and I'd like not to use it.

The command `/run as fake-op ...` is a bit verbose, you can use `command-alias` module to create your own command.
Here is the example config:
```
    "command_alias": {
      "enable": true,
      "alias": [
        {
          "from": [
            "sudo"
          ],
          "to": [
            "run",
            "as",
            "fake-op"
          ]
        }
      ]
    },
```

**Comment by sakurawald** [comment]
> > The `/sudo` is in `run module`, using: `/run as fake-op ...`. The output commands: are `/send-message`, `/send-broadcast`, `/send-title`, `/send-actionbar` and `/send-toast`.
> 
> Sudo with `sudo <name> c:Hi` will send a message to everybody, as that user. Like `/sudo Notch c:Hi!` `Notch: Hi!`
> 
> This can be .. kinda horribly recreated with fuji's current tools, but it just looks horrible. `/execute as @a run run as fake-op @s send-broadcast %fuji:player_prefix%%player:displayname_visual%%fuji:player_suffix%: Hi`

Hey, how about adding another command for this purpose? https://github.com/sakurawald/fuji-fabric/issues/68

**Comment by fucksophie** [comment]
> Hey, how about adding another command for this purpose? https://github.com/sakurawald/fuji-fabric/issues/68

Perfect! Exactly what I need.

**Comment by sakurawald** [comment]
completed in `fuji v1.5.1`
