### ISSUE TITLE
command cooldown not working

### ISSUE THREAD

**Issue by Ferbook3000** [fuji-fabric/fuji#8]
It looks like the cooldown is not working properly or maybe (probably) I do not understand how it works (would be great to have a wiki or discord where to ask simple questions).

It looks like this:
```
"command_cooldown": {
      "enable": true,
      "command_regex_2_cooldown_ms": {
        "download\\s*": 120000,
        "rw tp (overworld|the_nether|the_end)": 120000,
        "chunks\\s*": 60000,
        "crate comun": 86400,
        "hat": 86400
      }
```
But it's not working.
Help is appreciated.

**Comment by sakurawald** [comment]
Hello, the values in "command_regex_2_cooldown_ms" is the pattern of the commands.
The pattern is written in `regex` language.
You can read some examples on how to write `regex` language. (see: https://cs.lmu.edu/~ray/notes/regex/)

Sadly, there is still not an active discord group to ask questions.
The project is current in a in-active status, I am busy in some other works recently.
A more detailed wiki will be provided if I am spare.

However, you can ask questions in github issue

**Comment by sakurawald** [comment]
Hello, recently i am building a wiki in https://github.com/sakurawald/fuji-fabric/wiki/Configuration.
Please let met know any questions, and more parts you want to know.
