### ISSUE TITLE
Global permissions are ignored with zero-command-permission

### ISSUE THREAD

**Issue by 3ri4nG0ld** [fuji-fabric/fuji#9]
Until now I was using Lukyperms to manage permissions on my server, I have a Lobby created with paper and a mods server (in which I am using fuji), and both are connected with velocity.

On both servers and velocity I have installed Luckyperms configured in an external database.
This way all the permissions configured in velocity were applied in the rest of the servers, but when using zero-command-permission the permissions specified in velocity are ignored.

**Comment by sakurawald** [comment]
Fuji works with luckperms.

For every `command node`, luckperms defines a tri-state `permission predicate` ("true", "false" and "undefined")

Zero-command-permission will iterate all the registered `command-node` and check if there is a `relative zero-command` defined for the `command node`. If there is, then we wrapper the `original permission predicate` with the `zero-permission`.

If there is no relative zero-permission for the `command node`, then we do nothing. 
The `permission predicate` for the `command node` is never modified in this case.

See source: https://github.com/sakurawald/fuji-fabric/blob/1.20.4/src/main/java/io/github/sakurawald/module/initializer/zero_command_permission/ZeroCommandPermissionModule.java

Fuji check the permission by code `Permissions.getPermissionValue`, and it only contacts LuckPerms, never knows about velocity.
Maybe it's something about the permission sync between luckperms and velocity.

**Comment by sakurawald** [comment]
Hello, can you check this https://github.com/sakurawald/fuji-fabric/issues/20 and let me know if this situation still exists ?
